### ISSUE TITLE
Migrate from Heroku

### ISSUE THREAD

**Issue by sue445** [sue445/emoy_webhook#205]
c.f. [Heroku’s Next Chapter \| Heroku](https://blog.heroku.com/next-chapter)

# TODO
* [x] Distribute applications as Docker image
* [x] Run app on my account (e.g. Cloud Run)
* [x] Remove heroku from docs
* [x] Remove gems
  * rollbar
* [x] Write doc and changelog
